# Generated by Django 5.1.3 on 2024-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_project_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ManyToManyField(to="gallery.category"),
        ),
    ]
