# Generated by Django 5.1.3 on 2024-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_remove_project_category_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
