# Generated by Django 5.1.4 on 2025-05-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('single_mini', 'Single Miniature'), ('squad', 'Squad'), ('colossal', 'Colossal Vehicle/Monster'), ('terrain', 'Terrain')], max_length=20)),
                ('size_option', models.CharField(blank=True, max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assembly_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commission_uploads/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready to Checkout'), ('pending', 'Pending Manual Quote')], default='ready', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
