# Generated by Django 5.1.4 on 2025-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionquote_delete_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionquote',
            name='assembly_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionquote',
            name='priming_required',
            field=models.BooleanField(default=False),
        ),
    ]
