# Generated by Django 5.1.4 on 2025-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commissionquote_assembly_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionquote',
            name='priming_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='commissionquote',
            name='size_uplift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
