# Generated by Django 5.1.4 on 2025-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionquote_priming_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionquote',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
